version: '3.8'

services:
  app:
    image: ruby:3.2  # Specify the Ruby version you need
    working_dir: /app
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: bash -c "bundle install && RAILS_ENV=development rails assets:precompile && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"  # Expose Rails server on port 3000
    environment:
      RAILS_ENV: development
    tty: true  # Keep the terminal open
