name: CI/CD for Rails with Tailscale SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Test SSH Connection
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} "echo 'Connection successful!'" || echo "SSH connection failed"

      - name: Deploy to Homelab Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p 2222 -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} << 'EOF'
            cd blakeridgway
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
